services:
  queue:
    image: redis
  db:
    image: redis
  consumer:
    build:
      context: ./apps/consumer
      dockerfile: ../../config/Dockerfile
    environment:
      - OPENWEATHER_API_TOKEN
      - OPENWEATHER_API_URL=https://api.openweathermap.org/
    depends_on:
      - db
      - queue
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: ../../config/Dockerfile
    depends_on:
      - api
  api:
    build:
      context: ./apps/api
      dockerfile: ../../config/Dockerfile
    environment:
      - OPENWEATHER_API_TOKEN
      - OPENWEATHER_API_URL=https://api.openweathermap.org/
    depends_on:
      - db
      - queue
      - consumer
  routing:
    image: caddy
