export enum Topics {
  UPDATE_REQUEST_CHANNEL = "UPDATE_REQUEST",
  TRACK_LOCATION_CHANNEL = "TRACK_LOCATION",
  UNTRACK_LOCATION_CHANNEL = "UNTRACK_LOCATION",
  WEATHER_UPDATED_CHANNEL = "WEATHER_UPDATED",
}
